// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTfL9WBcK0_XqGON_wu4Nsq0kEHzjbpcQ',
    appId: '1:975700299038:web:0d55a93b333b0924424d0f',
    messagingSenderId: '975700299038',
    projectId: 'parcialdevmob',
    authDomain: 'parcialdevmob.firebaseapp.com',
    storageBucket: 'parcialdevmob.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8k9kMsfgOco4bBIM59roMPSGvmK9Hxk',
    appId: '1:975700299038:android:2ebeb279df9002c2424d0f',
    messagingSenderId: '975700299038',
    projectId: 'parcialdevmob',
    storageBucket: 'parcialdevmob.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-wZu0mRow9Y9fdqeozuQptzViZwusg3s',
    appId: '1:975700299038:ios:6b749341a29bb972424d0f',
    messagingSenderId: '975700299038',
    projectId: 'parcialdevmob',
    storageBucket: 'parcialdevmob.firebasestorage.app',
    iosClientId: '975700299038-sef1cev8k0t8v46tkc51nn1e6qt1656l.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcialDevmob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-wZu0mRow9Y9fdqeozuQptzViZwusg3s',
    appId: '1:975700299038:ios:6b749341a29bb972424d0f',
    messagingSenderId: '975700299038',
    projectId: 'parcialdevmob',
    storageBucket: 'parcialdevmob.firebasestorage.app',
    iosClientId: '975700299038-sef1cev8k0t8v46tkc51nn1e6qt1656l.apps.googleusercontent.com',
    iosBundleId: 'com.example.parcialDevmob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTfL9WBcK0_XqGON_wu4Nsq0kEHzjbpcQ',
    appId: '1:975700299038:web:0ad67f7d487f2f97424d0f',
    messagingSenderId: '975700299038',
    projectId: 'parcialdevmob',
    authDomain: 'parcialdevmob.firebaseapp.com',
    storageBucket: 'parcialdevmob.firebasestorage.app',
  );

}